extends: airbnb-base
plugins:
  - import

parserOptions:
  ecmaVersion: 2015

env:
  node: true
  browser: false
  es6: false

rules:
  no-console: off
  func-names: off
  max-len: off
  no-confusing-arrow: off
  object-shorthand: off
