language: node_js

node_js:
  - "12"
  - "10"
  - "8"

os:
  - linux
  - osx

env:
  - WEBPACK_VERSION=4
  - WEBPACK_VERSION=5.0.0-beta.11

install:
  - npm install
  - npm rm webpack
  - npm install webpack@$WEBPACK_VERSION || true

branches:
  only:
    - master
